export const ACCOUNTS_JS_SERVER = 'ACCOUNTS_JS_SERVER';
export const ACCOUNTS_JS_OPTIONS = 'ACCOUNTS_JS_OPTIONS';
export const ACCOUNTS_JS_OPTIONS_PROVIDER = 'ACCOUNTS_JS_OPTIONS_PROVIDER';
export const ACCOUNTS_DB = 'ACCOUNTS_DB';
export const ENABLE_FOR_ACCOUNTS_SERVICE = 'ENABLE_FOR_ACCOUNTS_SERVICE';
export const ACCOUNTS_JS_GRAPHQL = 'ACCOUNTS_JS_GRAPHQL';
export const AUTH_VALIDATOR_FUNCTIONS = 'AUTH_VALIDATOR_FUNCTIONS';
